project_id = "ofdlhkjtpyopayoxuzrz"

[functions.generate-success-analysis]
verify_jwt = false

[functions.download-resource]
verify_jwt = false

[functions.scrape-hub-event]
verify_jwt = false

[functions.scrape-eventbrite]
verify_jwt = false
